sonata_admin:
    security:

        # the default value
        handler: sonata.admin.security.handler.role

        # use this service if you want ACL
        handler: sonata.admin.security.handler.acl